
package test;

import  java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import  java.sql.Statement;
import  java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

public class stagiaire2 extends javax.swing.JFrame {

    /** Creates new form FormStagiaire */
  
    // Déclaration des variables.
 
    private DefaultTableModel dt; 
    private int cin;
    private String nom ,prenom,sexe;
    private String moyenne;
    private String dateNaiss;
    
    private int i; // un indice de déplacement 
      Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    public stagiaire2() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btng2 = new javax.swing.ButtonGroup();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtdur = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblestg = new javax.swing.JTable();
        btnPremier = new javax.swing.JButton();
        btnSuivant = new javax.swing.JButton();
        btnPrecedent = new javax.swing.JButton();
        btnDernier = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnRecherhcer = new javax.swing.JButton();
        txtrech = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtser = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jrb3 = new javax.swing.JRadioButton();
        jrb4 = new javax.swing.JRadioButton();
        jrb5 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtmat = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        comrech = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        setMinimumSize(new java.awt.Dimension(952, 597));
        setPreferredSize(new java.awt.Dimension(952, 597));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        txtid.setBackground(new java.awt.Color(73, 228, 169));
        getContentPane().add(txtid);
        txtid.setBounds(150, 140, 187, 22);

        txtnom.setBackground(new java.awt.Color(73, 228, 169));
        getContentPane().add(txtnom);
        txtnom.setBounds(150, 200, 187, 22);

        txtprenom.setBackground(new java.awt.Color(73, 228, 169));
        getContentPane().add(txtprenom);
        txtprenom.setBounds(150, 230, 187, 22);

        txtdur.setBackground(new java.awt.Color(73, 228, 169));
        getContentPane().add(txtdur);
        txtdur.setBounds(150, 300, 187, 22);

        jLabel1.setText("mat :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 170, 31, 16);

        jLabel2.setText("nom :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 200, 34, 16);

        jLabel3.setText("prenom :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 240, 53, 16);

        jLabel4.setText("Service :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 270, 51, 16);

        jLabel5.setText("dureé de stage");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 300, 86, 16);

        tblestg.setBackground(new java.awt.Color(73, 228, 169));
        tblestg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "mat", "nom", "prenom", "service", "duree", "sexe"
            }
        ));
        tblestg.setGridColor(new java.awt.Color(73, 228, 169));
        tblestg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblestgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblestg);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 140, 440, 220);

        btnPremier.setBackground(new java.awt.Color(73, 228, 169));
        btnPremier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPremier.setText("précédent");
        btnPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPremierActionPerformed(evt);
            }
        });
        getContentPane().add(btnPremier);
        btnPremier.setBounds(120, 380, 109, 20);

        btnSuivant.setBackground(new java.awt.Color(73, 228, 169));
        btnSuivant.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSuivant.setText("dernier");
        btnSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivantActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivant);
        btnSuivant.setBounds(350, 380, 100, 20);

        btnPrecedent.setBackground(new java.awt.Color(73, 228, 169));
        btnPrecedent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrecedent.setText("Premier");
        btnPrecedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrecedentActionPerformed(evt);
            }
        });
        getContentPane().add(btnPrecedent);
        btnPrecedent.setBounds(10, 380, 100, 20);

        btnDernier.setBackground(new java.awt.Color(73, 228, 169));
        btnDernier.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDernier.setText("Suivant");
        btnDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDernierActionPerformed(evt);
            }
        });
        getContentPane().add(btnDernier);
        btnDernier.setBounds(250, 380, 90, 20);

        btnAjouter.setBackground(new java.awt.Color(73, 228, 169));
        btnAjouter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ajouter.png"))); // NOI18N
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });
        getContentPane().add(btnAjouter);
        btnAjouter.setBounds(30, 420, 170, 50);

        btnModifier.setBackground(new java.awt.Color(73, 228, 169));
        btnModifier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/modifier.png"))); // NOI18N
        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnModifier);
        btnModifier.setBounds(220, 420, 170, 50);

        btnSupprimer.setBackground(new java.awt.Color(73, 228, 169));
        btnSupprimer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/supprimer.png"))); // NOI18N
        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnSupprimer);
        btnSupprimer.setBounds(30, 490, 170, 50);

        btnRecherhcer.setBackground(new java.awt.Color(73, 228, 169));
        btnRecherhcer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRecherhcer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/rechercher.png"))); // NOI18N
        btnRecherhcer.setText("Rechercher");
        btnRecherhcer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecherhcerActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecherhcer);
        btnRecherhcer.setBounds(740, 420, 180, 60);

        txtrech.setBackground(new java.awt.Color(73, 228, 169));
        txtrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrechActionPerformed(evt);
            }
        });
        getContentPane().add(txtrech);
        txtrech.setBounds(570, 470, 160, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Rechercher par :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 420, 130, 70);

        txtser.setBackground(new java.awt.Color(73, 228, 169));
        txtser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "informatique", "gestion et recrutment", "maintenance", "logistique", "fiscale", "transport" }));
        getContentPane().add(txtser);
        txtser.setBounds(150, 270, 187, 22);

        jLabel7.setText("sexe :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 340, 35, 16);

        btng2.add(jrb3);
        jrb3.setText("masculin");
        jrb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb3ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb3);
        jrb3.setBounds(100, 340, 79, 25);

        btng2.add(jrb4);
        jrb4.setText("féminin");
        jrb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb4ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb4);
        jrb4.setBounds(200, 340, 71, 25);

        btng2.add(jrb5);
        jrb5.setText("autre");
        jrb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb5ActionPerformed(evt);
            }
        });
        getContentPane().add(jrb5);
        jrb5.setBounds(290, 340, 59, 25);

        jLabel8.setText("ID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 140, 12, 16);

        txtmat.setBackground(new java.awt.Color(73, 228, 169));
        getContentPane().add(txtmat);
        txtmat.setBounds(150, 170, 187, 22);

        jButton3.setBackground(new java.awt.Color(73, 228, 169));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/actualiser .png"))); // NOI18N
        jButton3.setText("actualiser");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(220, 490, 170, 50);

        comrech.setBackground(new java.awt.Color(73, 228, 169));
        comrech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        comrech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "mat", "nom", "prenom", "service", "duree", "sexe" }));
        getContentPane().add(comrech);
        comrech.setBounds(570, 390, 160, 50);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ahmed\\Desktop\\java\\toph.jpg")); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 950, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
//          Load FormStagiaire
    
    
private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
   jrb3.setSelected(true);
    try{
        // connexion avec base de donnée stg
        Class.forName("com.mysql.jdbc.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/stg","root","estsb");
      st = con.createStatement();
     
      btng2.add(jrb3);
        btng2.add(jrb4);
        btng2.add(jrb5);
      
        dt = new DefaultTableModel();// dt c'est un variable pour stocké les element d'un tableau {ligne et colomn}
      
        dt.addColumn("cin");
        dt.addColumn("nom");
        dt.addColumn("prenom");
        dt.addColumn("service");
        dt.addColumn("duree");
        dt.addColumn("sexe");
       tblestg.setModel(dt);
        // afficehr la liste des stagiaires
        AfficherStagiaire();
        // remplir les champs 
         i = 0;
        DeplacerStagiaire(i);
    }catch(Exception e){
        System.out.printf("erreur   "+e.getMessage());//getMessage c'est une fonction  pour afficher l'Erreur ou se trouve ?!!!!!
        JOptionPane.showMessageDialog(null, "Erreur de connexion\n  "+ e.getMessage());
    }
}//GEN-LAST:event_formWindowOpened

//          PREMIER
private void btnPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPremierActionPerformed
 try{
        i--;
        DeplacerStagiaire(i);
        // ou DeplacerStagiaire(--i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnPremierActionPerformed
//          PRECEDENT
private void btnPrecedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrecedentActionPerformed
    try{
        i = 0;
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());}
}//GEN-LAST:event_btnPrecedentActionPerformed
//          SUIVANT
private void btnSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivantActionPerformed
    try{
        i = dt.getRowCount() - 1 ; //
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnSuivantActionPerformed
//          DERNIER
private void btnDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDernierActionPerformed
    try{
        i++;
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur premier !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnDernierActionPerformed
//          selectionnéé stg
private void tblestgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblestgMouseClicked
       try{
        i = tblestg.getSelectedRow(); // getSelectedRow() fonction nous retourne le ligne selectionner par l utilisateur
         
        DeplacerStagiaire(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur selectionnéé stg\n"+e.getMessage());
    }
}//GEN-LAST:event_tblestgMouseClicked

//          Ajouter stg
private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
    try{
   
String sql = "INSERT INTO stagiaire  (nom,prenom,service,dure,sexe)VALUES (?,?,?,?,?)";
         PreparedStatement ps = con.prepareStatement(sql);
         ps.setString(1, txtmat.getText());
      ps.setString(2, txtnom.getText());
      ps.setString(3, txtprenom.getText());
      ps.setString(4, txtser.getSelectedItem().toString());
      ps.setString(5, txtdur.getText());
      ps.setString(6, sexe);
    
      
      ps.executeUpdate();
      AfficherStagiaire(); // recharger la liste des stagiaires
            JOptionPane.showMessageDialog(null, "Stagiaire est ajouté");
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur ajouter stg\n"+e.getMessage());
        System.err.println(""+e.getMessage());
    }
}//GEN-LAST:event_btnAjouterActionPerformed
//          MODIFIER stg
private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
    try{ 
        // msg d confirmation !
        if (JOptionPane.showConfirmDialog(null, "confirmer la modification","modification sur un stagaire",
                JOptionPane.YES_NO_OPTION) == JOptionPane.OK_OPTION){
           st.executeUpdate("UPDATE stagaire SET nom='"+txtnom.getText()
      +"',prenom='"+txtprenom.getText()+"',service='"+txtser.getSelectedItem().toString()
                   +"',dure='"+txtdur.getText()+"',sexe='"+sexe
                   +"' WHERE id = "+ txtid.getText());       
           //lorseque en fait +txtfield.gettext+ en doit ecrit les appostrophe ""
  
           AfficherStagiaire(); // recharger la liste des stagiaires
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur modifier stg\n"+e.getMessage());
    }
}//GEN-LAST:event_btnModifierActionPerformed
//          supprimer stg
private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
    try{
        if(JOptionPane.showConfirmDialog(null, "attention est tu es sure que"
                + " tu veux supprimer ce stagaire","Supprimer stagaire",JOptionPane.YES_NO_OPTION)
                == JOptionPane.OK_OPTION){
   //si textfield id est vide ,on peux pas supprimmer
                st.executeUpdate("Delete from stagaire where id = "+ txtid.getText());
                AfficherStagiaire(); // recharger la liste des stagiaires ...
           
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur supprimer stg !\n"+e.getMessage());
    }
}//GEN-LAST:event_btnSupprimerActionPerformed


private void btnRecherhcerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecherhcerActionPerformed
try { 
    dt.setRowCount(0); //pour vider tableau 
    Statement st = con.createStatement();
        ResultSet rs = st.executeQuery( "SELECT * FROM stagaire WHERE "+combo()
                +"  like '%"+txtrech.getText()+"%'" );
    
     while(rs.next()){
            cin=rs.getInt(1);
            nom = rs.getString(3);
            prenom = rs.getString(4);
            moyenne = rs.getString(5);
            dateNaiss = rs.getString(6);
            sexe=rs.getString(7);
            
            Object[] stg = {id,mat,nom,prenom,moyenne,dateNaiss,sexe};
            dt.addRow(stg);
        }
     
        if (dt.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Aucun Stagiaire");
            AfficherStagiaire(); // afficher tout les stgs
        }else{
            i = 0;
            DeplacerStagiaire(i);
        }
    
}catch (Exception m){JOptionPane.showMessageDialog(null, ""+m.getMessage());
System.err.println(m);}
}//GEN-LAST:event_btnRecherhcerActionPerformed

    private void jrb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb3ActionPerformed
sexe=jrb3.getText();  
// TODO add your handling code here:
    }//GEN-LAST:event_jrb3ActionPerformed

    private void jrb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb4ActionPerformed
sexe=jrb4.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jrb4ActionPerformed

    private void jrb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb5ActionPerformed
sexe=jrb5.getText();        // TODO add your handling code here:
    }//GEN-LAST:event_jrb5ActionPerformed

    private void txtrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrechActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
actualiser();
AfficherStagiaire();// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    

       String combo(){
switch(comrech.getSelectedIndex()){ 
        case 0: return "cin";
        case 1: return "nom";
        case 2: return "prenom";
        case 3: return "service";
        case 4: return "dure";
        case 5: return "sexe";
      }
      return "";
}
    
    private void DeplacerStagiaire(int i){
    try{
        if (dt.getRowCount() == 0){ //si il y aucun enregistrement tableau est vide
            btnPrecedent.setEnabled(false);
            btnSuivant.setEnabled(false);
            actualiser();
        }else{
            if(i == 0){ //si i est localiser sur le premier enregistrement  
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(true);
                }else if (i == dt.getRowCount()-1){ //  si i est localisé sur  dernier enregistrement
                btnPrecedent.setEnabled(true);
            btnSuivant.setEnabled(false);
            }else{
                btnPrecedent.setEnabled(true);
                btnSuivant.setEnabled(true);
            }
            if(dt.getRowCount() == 1){//si il y a un seul enregistrement, nous avons un seul ligne
                btnPrecedent.setEnabled(false);
                btnSuivant.setEnabled(false);
            }
        }
        
        txtid.setText(dt.getValueAt(i, 0).toString()); 
        txtmat.setText(dt.getValueAt(i, 1).toString()); // i represente numero d ligne ,et 0 1 .. colonne
        txtnom.setText(dt.getValueAt(i, 2).toString()); // lorseque i=1 getValueAt nous retourne le premier ligne si i=2 le ligne ......
       txtprenom.setText(dt.getValueAt(i, 3).toString());
        txtser.setSelectedItem(dt.getValueAt(i, 4).toString());
        txtdur.setText(dt.getValueAt(i, 5).toString());
        String s = dt.getValueAt(i, 6).toString();
        if(s.equals("masculin")){jrb3.setSelected(true);}else if(s.equals("féminin")){jrb4.setSelected(true);}
        else {jrb5.setSelected(true);}
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur deplacement stagiaire\n"+e.getMessage());
    }
}
//          procedure qui Afficher la liste des Stagiaire.


private void AfficherStagiaire(){
  
   txtid.setEnabled(false);
   
     try{
        dt.setRowCount(0); // vider la list des stagiaires.
        rs = st.executeQuery("Select * From stagaire");
        
        while(rs.next()){
           int cin=rs.getInt("cin");
            nom = rs.getString("nom");
            prenom = rs.getString("prenom");
            moyenne = rs.getString("service");
            dateNaiss = rs.getString("dure");
             sexe = rs.getString("sexe");
            Object[] stg = {id,nom,prenom,moyenne,dateNaiss,sexe};
            dt.addRow(stg);
        }
    }catch(Exception e){
        JOptionPane.showMessageDialog(null, "Erreur afficher la liste des stagiaire\n"+e.getMessage());
    }
    

}
public void actualiser(){ // fonction de type void ne retourne rien !!!!!!??
txtid.setText("");
            txtnom.setText("");
            txtprenom.setText("");
            txtser.setSelectedItem(1);
            jrb4.isSelected();
            txtdur.setText("");
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stagiaire2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stagiaire2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stagiaire2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stagiaire2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new stagiaire2().setVisible(true);
            }
        });
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnDernier;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnPrecedent;
    private javax.swing.JButton btnPremier;
    private javax.swing.JButton btnRecherhcer;
    private javax.swing.JButton btnSuivant;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.ButtonGroup btng2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox comrech;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jrb3;
    private javax.swing.JRadioButton jrb4;
    private javax.swing.JRadioButton jrb5;
    private javax.swing.JTable tblestg;
    private javax.swing.JTextField txtdur;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtmat;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtrech;
    private javax.swing.JComboBox txtser;
    // End of variables declaration//GEN-END:variables
    //
}